# Generated by Django 3.0 on 2019-12-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('prime', models.CharField(default=' ', max_length=100, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('code', models.IntegerField()),
            ],
            options={
                'db_table': 'Favorite',
            },
        ),
    ]
