# Generated by Django 2.2.6 on 2019-11-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20191130_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='code',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
