# Generated by Django 2.2.6 on 2019-12-01 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20191201_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('market', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Company',
            },
        ),
        migrations.AlterField(
            model_name='price',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Company'),
        ),
    ]
