# Generated by Django 2.2.6 on 2019-12-01 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_auto_20191202_0024'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='price',
            unique_together=set(),
        ),
    ]
