# Generated by Django 2.2.6 on 2019-12-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_auto_20191202_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='id',
        ),
        migrations.AddField(
            model_name='price',
            name='prime',
            field=models.CharField(default=' ', max_length=100, primary_key=True, serialize=False),
        ),
    ]
