# Generated by Django 2.2.6 on 2019-12-07 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_auto_20191202_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjust',
            fields=[
                ('prime', models.CharField(default=' ', max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('constant', models.FloatField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Company')),
            ],
            options={
                'db_table': 'Adjust',
            },
        ),
    ]
